# Specify the base image
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application files
COPY . .

# Build the React app
RUN npm run build

# Expose the port
EXPOSE 3000

# Start the container
CMD [ "npm", "start" ]

